services:
    postgres:
        image: savvas25/k2-pos-postgres:latest
        build:
            context: ./postgres
            dockerfile: Dockerfile
        env_file:
            - env/postgres.env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql

    rest-api:
        image: savvas25/k2-pos-rest-api:latest
        depends_on:
            - postgres
        build:
            context: ../pos-api/
            dockerfile: ../web-pos-docker/rest-api/Dockerfile
        env_file:
            - env/rest-api.env
            - env/postgres.env
        ports:
            - "8080:8080"

        volumes:
            -   ./volumes/rest-api-logs:/app/logs

    web-app:
        image: savvas25/k2-pos-web-app:latest
        depends_on:
            - rest-api
        build:
            context: ../pos-web/
            dockerfile: ../web-pos-docker/web-app/Dockerfile
        environment:
            - API_URL=http://rest-api:8080
        ports:
            - "80:80"

        volumes:
            -   ./volumes/web-app-logs:/app/logs

volumes:
    postgres_data: