name: Docker Hub Login

on:
  workflow_dispatch:
  push:
    branches:
      - cicid

jobs:
  docker-login:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: savvas25
          password: dckr_pat_0hK9iX9hjH8vkD5y64YQ_Hup7jQ

      - name: Confirm login
        run: echo "Successfully logged in to Docker Hub"

